### ISSUE TITLE
Automation Tools cannot be installed

### ISSUE THREAD

**Issue by carsonchung1** [srl-labs/sros-anysec-macsec-lab#40]
venv) client7:/flask_app# HTTPS_PROXY= HTTP_PROXY= http_proxy= https_proxy= flask run --host=0.0.0.0 &
sleep 3
[2] 167
(venv) client7:/flask_app# Exception in thread Thread-2 (sub_telemetry):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Traceback (most recent call last):
  File "/flask_app/venv/bin/flask", line 8, in <module>
    sys.exit(main())
    self.run()
             ^^^^^^
  File "/usr/lib/python3.11/threading.py", line 982, in run
  File "/flask_app/venv/lib/python3.11/site-packages/flask/cli.py", line 1105, in main
    self._target(*self._args, **self._kwargs)
  File "/flask_app/app.py", line 106, in sub_telemetry
    cli.main()
    with gNMIclient(
  File "/flask_app/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 143, in __enter__
    return self.connect()
           ^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 291, in connect
    self.wait_for_connect(timeout)
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 313, in wait_for_connect
    rv = self.invoke(ctx)
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
         ^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/grpc/_utilities.py", line 162, in result
  File "/flask_app/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    self._block(timeout)
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/flask_app/venv/lib/python3.11/site-packages/grpc/_utilities.py", line 106, in _block
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/flask/cli.py", line 953, in run_command
    raise e from None
  File "/flask_app/venv/lib/python3.11/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/flask/cli.py", line 335, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/flask_app/app.py", line 382, in <module>
    telemetry.run()
  File "/flask_app/app.py", line 215, in run
    self.update_port_status(host_entry)
  File "/flask_app/app.py", line 155, in update_port_status
    with gNMIclient(
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 143, in __enter__
    return self.connect()
           ^^^^^^^^^^^^^^
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 291, in connect
    self.wait_for_connect(timeout)
  File "/flask_app/venv/lib/python3.11/site-packages/pygnmi/client.py", line 313, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/flask_app/venv/lib/python3.11/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/flask_app/venv/lib/python3.11/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

**Comment by hellt** [comment]
since #38 has been merged, the refreshed automation panel is now in place. This issue should be solved automatically
