### ISSUE TITLE
panel container crashing

### ISSUE THREAD

**Issue by sacckth** [srl-labs/sros-anysec-macsec-lab#46]
```
root@bugatti9:/usr/local/bugatti9/sros-anysec-macsec-lab# docker logs panel

> frontend@0.0.1 preview
> vite preview --host 0.0.0.0

  ➜  Local:   http://localhost:4173/
  ➜  Network: http://172.50.50.33:4173/
TypeError: fetch failed
    at node:internal/deps/undici/undici:12500:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve2 (file:///app/.svelte-kit/output/server/index.js:2781:14)
    at async respond (file:///app/.svelte-kit/output/server/index.js:2605:22)
    at async fetch (file:///app/.svelte-kit/output/server/index.js:2365:26) {
  [cause]: Error: connect ECONNREFUSED 127.0.1.1:54173
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.1.1',
    port: 54173
  }
}
TypeError: Cannot read properties of undefined (reading 'vll')
    at file:///app/.svelte-kit/output/server/entries/pages/_page.svelte.js:50:329
    at each (file:///app/.svelte-kit/output/server/chunks/ssr.js:63:12)
    at file:///app/.svelte-kit/output/server/entries/pages/_page.svelte.js:48:13
    at Object.$$render (file:///app/.svelte-kit/output/server/chunks/ssr.js:93:18)
    at file:///app/.svelte-kit/output/server/entries/pages/_page.svelte.js:107:111
    at Object.$$render (file:///app/.svelte-kit/output/server/chunks/ssr.js:93:18)
    at Object.default (file:///app/.svelte-kit/output/server/chunks/internal.js:73:98)
    at file:///app/.svelte-kit/output/server/entries/pages/_layout.svelte.js:3:42
    at Object.$$render (file:///app/.svelte-kit/output/server/chunks/ssr.js:93:18)
    at file:///app/.svelte-kit/output/server/chunks/internal.js:62:121
2024/10/11 00:04:06 pe1:57400: context deadline exceeded
```

**Comment by sacckth** [comment]
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
❯ uname -a
Linux bugatti9 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
